# Generated by Django 2.1.7 on 2019-03-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_text', models.CharField(max_length=50, verbose_name='AccountType')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=50, verbose_name='Username')),
                ('first_name_text', models.CharField(max_length=50, verbose_name='FirstName')),
                ('last_name_text', models.CharField(max_length=50, verbose_name='LastName')),
                ('join_date', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
        migrations.AddField(
            model_name='accounttype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
