# Generated by Django 2.1.7 on 2019-03-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_type_text',
            field=models.CharField(db_column='AccountType', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_text',
            field=models.CharField(db_column='FirstName', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(db_column='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_text',
            field=models.CharField(db_column='LastName', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_text',
            field=models.CharField(db_column='Username', max_length=50),
        ),
    ]
